### ISSUE TITLE
Why are transactions removed in default/initial/historical_update hooks?

### ISSUE THREAD

**Issue by sarink** [plaid/pattern#208]
Per the docs:
> Plaid does not model the transition of a pending to posted transaction as a state change for an existing transaction; instead, the posted transaction is a new transaction with a pending_transaction_id field that matches it to a corresponding pending transaction. When a pending transaction is converted to a posted transaction, Plaid removes the pending transaction, sends a [TRANSACTIONS_REMOVED](https://plaid.com/docs/api/webhooks/#transactions-transactions_removed) webhook, and returns the new, posted transaction.

Yet, https://github.com/plaid/pattern/blob/master/server/webhookHandlers/handleTransactionsWebhook.js#L109
```
  // Compare to find removed transactions (pending transactions that have posted or cancelled).
  const incomingTransactionIds = incomingTransactions.reduce(
    (idMap, { transaction_id: transactionId }) => ({
      ...idMap,
      [transactionId]: transactionId,
    }),
    {}
  );
  const transactionsToRemove = existingTransactions.filter(
    ({ plaid_transaction_id: transactionId }) => {
      const isIncoming = incomingTransactionIds[transactionId];
      return !isIncoming;
    }
  );
```

If pending/canceled transactions always fire a `TRANSACTIONS_REMOVED` webhook, shouldn't that be the _only_ place transactions ever get deleted? Why is there this code to remove transactions during the other webhooks as well?

**Comment by lindawoo-plaid** [comment]
Hi @sarink , Yes, in THEORY it should be safe to always listen to TRANSACTIONS_REMOVED and that will take care of the only place necessary to delete transactions.  However, since it is impossible to guarantee the receipt of every webhook, we have suggested that customers listen for the TRANSACTIONS_REMOVED but also fall back on comparing transaction history to their own database to figure out what's disappeared in order to avoid duplicates. 

We are currently building a new update model and API to address these sorts of issues to avoid this sort of confusion in the future.
