### ISSUE TITLE
Valid test user added in sandbox won't load in pattern

### ISSUE THREAD

**Issue by meysammohajer** [plaid/pattern#315]
Hi, I created a json file based on [this format](https://github.com/plaid/sandbox-custom-users/blob/d630bdfcf85bf851c3cc3d70ea9c114a48d21b6f/assets/assets_custom_user.json) and I used it to create a test user in my sanbox. But when I try to load that valid user in pattern it's not working and it just get stuck. Here is my json file. [sample-user.json](https://github.com/user-attachments/files/17654085/sample-user.json)

<img width="1781" alt="Screenshot 2024-11-03 at 7 29 14 PM" src="https://github.com/user-attachments/assets/abb7171f-eda2-41ce-ad5a-23185b7035fa">

Also when I try to fetch transactions (below code) for that user in sandbox, it seems it get stuck in the while loop. I'd appreciate any feedback on this. Thanks!  

`def get_transactions(access_token: str):
    # Set cursor to empty to receive all historical updates
    cursor = ''

    # New transaction updates since "cursor"
    added = []
    modified = []
    removed = []  # Removed transaction ids
    has_more = True
    try:
        # Iterate through each page of new transaction updates for item
        while has_more:
            request = TransactionsSyncRequest(
                access_token=access_token,
                cursor=cursor,
            )
            response = client.transactions_sync(request).to_dict()
            cursor = response['next_cursor']
            print(f"cursor: {cursor}") # cursor is always empty for our custom data!!!

            if cursor == '':
                time.sleep(2)
                continue
                # If cursor is not an empty string, we got results,
            # so add this page of results
            added.extend(response['added'])
            modified.extend(response['modified'])
            removed.extend(response['removed'])
            has_more = response['has_more']

        # Return all transactions
        all_transactions = sorted(added, key=lambda t: t['date'])
        return all_transactions

    except plaid.ApiException as e:
        error_response = json.loads(e.body)
        return error_response`

**Comment by phoenixy1** [comment]
I haven't tried to reproduce this, but one thing that jumps out at me is that your user's transactions are all in 2023. Because the Pattern app does not use the `transactions.days_requested` field, it requests the default 90 days of transaction history rather than the maximum 730 days available. As a result, it won't see any transaction history for this user. 

To avoid this, you should either update the transaction dates for your test user to be within the last 90 days, or update the `/link/token/create` call used by the pattern app to set the `transactions.days_requested` field. See https://plaid.com/docs/api/link/#link-token-create-request-transactions-days-requested for more details.
